// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"beego-app/conf"
	"beego-app/conf/orm"
	"beego-app/controller"
	"beego-app/usecase"
	orm2 "github.com/beego/beego/v2/client/orm"
)

// Injectors from wire.go:

func InitializeAppProperties() *conf.AppProperties {
	dataSourceProperties := orm.NewDataSourceProperties()
	dbProps := orm.NewDbProps(dataSourceProperties)
	appProperties := conf.NewAppProperties(dbProps)
	return appProperties
}

func InitializeUserHandler(db orm2.Ormer) *controller.UserController {
	userService := usecase.NewUserService(db)
	userController := controller.NewUserController(userService)
	return userController
}
