// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"beego-app/conf"
	"beego-app/conf/datasource"
	"beego-app/controller"
	"beego-app/usecase"
)

// Injectors from wire.go:

func InitializeAppProperties() *conf.AppProperties {
	dataSourceProperties := datasource.NewDataSourceProperties()
	dbProps := datasource.NewDbProps(dataSourceProperties)
	appProperties := conf.NewAppProperties(dbProps)
	return appProperties
}

func InitializeUserHandler() *controller.UserController {
	userService := usecase.NewUserService()
	userController := controller.NewUserController(userService)
	return userController
}
